/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import GUI.valoresInterfaz.ListaSimple;
import GUI.valoresInterfaz.valoresGuardados;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import proyectograafo.Grafo;

/**
 *
 * @author joseg
 */
public class Menu2IntroducirCiclosHormigas extends javax.swing.JFrame {
    //para verificar que los obligatorios se hayan cumplido.
    valoresGuardados contenedorValores;
    ListaSimple paramObligatorioCiclos;
    ListaSimple paramObligatorioHormigas;
    ListaSimple paramOpcionalAlfa;
    ListaSimple paramOpcionalBeta;
    JFrame warningIntroducirParamObligatorios;
    
    
    static Grafo grafo;
    
    public static Menu1AgregarEliminarCargarIniciar vMenu2; 
    /**
     * Creates new form Menu2IntroducirCiclosHormigas
     */
    public Menu2IntroducirCiclosHormigas(Menu1AgregarEliminarCargarIniciar vMenu2) {
        initComponents();
        //grafo = G;
        this.vMenu2=vMenu2;
        vMenu2.setVisible(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.paramObligatorioCiclos=new ListaSimple();
        this.paramObligatorioHormigas=new ListaSimple();
        this.paramOpcionalAlfa=new ListaSimple();
        this.paramOpcionalBeta=new ListaSimple();
        this.contenedorValores=new valoresGuardados(paramObligatorioHormigas, paramObligatorioCiclos, paramOpcionalAlfa, paramOpcionalBeta);
                }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Agregar = new javax.swing.JButton();
        iniciarSimulación = new javax.swing.JButton();
        cargarGrafo = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        volverMenu1menu2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        escribirParametrobeta = new javax.swing.JTextField();
        entrarParametrobeta = new javax.swing.JButton();
        entrarParametroalfa = new javax.swing.JButton();
        escribirParametroalfa = new javax.swing.JTextField();
        entrarNumerohormigasmenu2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        entrarNumerodeciclosmenu2 = new javax.swing.JButton();
        escribirNumerodeciclosmenu2 = new javax.swing.JTextField();
        escribirNumerohormigasmenu2 = new javax.swing.JTextField();
        iniciarViajemenu2 = new javax.swing.JButton();
        Agregar2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Una vez que se llenen los parametros obligatorios, aparecerá el botón \"INICIAR VIAJE\"");

        jLabel8.setText("Son opcionales: Por default las variables son α=1  y ß=2");

        Agregar.setText("Introducir número de ciclos");

        iniciarSimulación.setText("Introducir número de hormigas");
        iniciarSimulación.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarSimulaciónActionPerformed(evt);
            }
        });

        cargarGrafo.setText("Entrar parametro de Importancia α");
        cargarGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarGrafoActionPerformed(evt);
            }
        });

        Eliminar.setText("Entrar parametro de visibilidad ß");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        jLabel6.setText("Parametros opcionales");

        jLabel5.setText("Parametros obligatorios");

        jLabel4.setText("Antes de iniciar la simulación, es necesario introducir parametros. ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Valores de simulación");

        jButton2.setText("Volver a menu");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("No debe apretar el botón \"INICIAR VIAJE\" sino hasya haber llenado los parametros opcionales");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 264, -1, 10));

        jLabel11.setText("Son opcionales: Por default las variables son α=1  y ß=2");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        jLabel13.setText("Antes de iniciar la simulación, es necesario introducir parametros. ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 430, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setText("Valores de simulación");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        volverMenu1menu2.setText("Volver a menú");
        volverMenu1menu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverMenu1menu2ActionPerformed(evt);
            }
        });
        getContentPane().add(volverMenu1menu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(escribirParametrobeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 40, -1));

        entrarParametrobeta.setText("Entrar parametro de visibilidad ß");
        entrarParametrobeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarParametrobetaActionPerformed(evt);
            }
        });
        jPanel1.add(entrarParametrobeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));

        entrarParametroalfa.setText("Entrar parametro de Importancia α");
        entrarParametroalfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarParametroalfaActionPerformed(evt);
            }
        });
        jPanel1.add(entrarParametroalfa, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 220, -1));
        jPanel1.add(escribirParametroalfa, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 40, -1));

        entrarNumerohormigasmenu2.setText("Introducir número de hormigas");
        entrarNumerohormigasmenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarNumerohormigasmenu2ActionPerformed(evt);
            }
        });
        jPanel1.add(entrarNumerohormigasmenu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 200, -1));

        jLabel12.setText("Parametros obligatorios");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel7.setText("Parametros opcionales");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));

        entrarNumerodeciclosmenu2.setText("Introducir número de ciclos");
        entrarNumerodeciclosmenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarNumerodeciclosmenu2ActionPerformed(evt);
            }
        });
        jPanel1.add(entrarNumerodeciclosmenu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));
        jPanel1.add(escribirNumerodeciclosmenu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 40, -1));

        escribirNumerohormigasmenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escribirNumerohormigasmenu2ActionPerformed(evt);
            }
        });
        jPanel1.add(escribirNumerohormigasmenu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 40, -1));

        iniciarViajemenu2.setText("Iniciar viaje");
        iniciarViajemenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarViajemenu2ActionPerformed(evt);
            }
        });
        jPanel1.add(iniciarViajemenu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -30, 650, 410));

        Agregar2.setText("Introducir número de ciclos");
        Agregar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar2ActionPerformed(evt);
            }
        });
        getContentPane().add(Agregar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/ANT CARD sunset.jpg"))); // NOI18N
        jLabel14.setText("jLabel2");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(-330, -20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarSimulaciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarSimulaciónActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iniciarSimulaciónActionPerformed

    private void cargarGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarGrafoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cargarGrafoActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarActionPerformed

    private void entrarNumerohormigasmenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarNumerohormigasmenu2ActionPerformed
this.contenedorValores.insertarHormiga(Integer.parseInt(this.escribirNumerohormigasmenu2.getText()));
    }//GEN-LAST:event_entrarNumerohormigasmenu2ActionPerformed

    private void entrarParametrobetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarParametrobetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entrarParametrobetaActionPerformed

    private void entrarParametroalfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarParametroalfaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entrarParametroalfaActionPerformed

    private void entrarNumerodeciclosmenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarNumerodeciclosmenu2ActionPerformed
this.contenedorValores.insertarCiclos(Integer.parseInt(this.escribirNumerodeciclosmenu2.getText()));
    }//GEN-LAST:event_entrarNumerodeciclosmenu2ActionPerformed

    private void Agregar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Agregar2ActionPerformed

    private void iniciarViajemenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarViajemenu2ActionPerformed
        if(this.contenedorValores.recuperarParamObligatorioCiclo()==null || this.contenedorValores.recuperarParamObligatorioHormigas()==null){
            warningIntroducirParamObligatorios=new JFrame();
            JOptionPane.showMessageDialog(warningIntroducirParamObligatorios, "Necesitas introducir los parametros obligatorios correspondientes a hormiga y ciclo antes de iniciar simulación.", "Alert", JOptionPane.WARNING_MESSAGE);
        }else{
            Menu3FinalizarGrafoGuardar vMenu3=new Menu3FinalizarGrafoGuardar(this);
vMenu3.setVisible(true); //hola
this.toFront();
            
        }
    }//GEN-LAST:event_iniciarViajemenu2ActionPerformed

    private void volverMenu1menu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverMenu1menu2ActionPerformed
     this.toBack();
setVisible(false); /**
 * @param false es para indicar que al devolverse en el programa, esta ventana "this" requiere irse.
 */
new GUI.Menu1AgregarEliminarCargarIniciar().setState(java.awt.Frame.NORMAL);
/**
 * @param NORMAL en setState es para indicar que es la ventana referenciada es el estado "normal" de una aplicación.
 */
    }//GEN-LAST:event_volverMenu1menu2ActionPerformed

    private void Volvermenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Volvermenu1ActionPerformed

        
    }//GEN-LAST:event_Volvermenu1ActionPerformed

    private void escribirNumerohormigasmenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escribirNumerohormigasmenu2ActionPerformed
    }//GEN-LAST:event_escribirNumerohormigasmenu2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu2IntroducirCiclosHormigas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu2IntroducirCiclosHormigas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu2IntroducirCiclosHormigas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu2IntroducirCiclosHormigas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Menu2IntroducirCiclosHormigas(vMenu2).setVisible(true); //aqui estaba un grafo en los parametros
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JButton Agregar2;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton cargarGrafo;
    private javax.swing.JButton entrarNumerodeciclosmenu2;
    private javax.swing.JButton entrarNumerohormigasmenu2;
    private javax.swing.JButton entrarParametroalfa;
    private javax.swing.JButton entrarParametrobeta;
    private javax.swing.JTextField escribirNumerodeciclosmenu2;
    private javax.swing.JTextField escribirNumerohormigasmenu2;
    private javax.swing.JTextField escribirParametroalfa;
    private javax.swing.JTextField escribirParametrobeta;
    private javax.swing.JButton iniciarSimulación;
    private javax.swing.JButton iniciarViajemenu2;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton volverMenu1menu2;
    // End of variables declaration//GEN-END:variables
}
