/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import GUI.Menu2IntroducirCiclosHormigas;
import javax.swing.JOptionPane;
import proyectograafo.*;

/**
 *
 * @author joseg
 */
public class Menu1AgregarEliminarCargarIniciar extends javax.swing.JFrame {
    public static Grafo grafo = new Grafo(); //Ok, trate de que sea static para que este grafo se compartiese en todos los grafos y pudiese verse igual, entonces nada.
    public static Menu1AgregarEliminarCargarIniciar vMenu1;
    /**
     * Creates new form menuAgregarEliminarCargarIniciar
     */
    
    public Menu1AgregarEliminarCargarIniciar(Grafo grafo) {
        initComponents(); 
        this.vMenu1=vMenu1;
        this.setVisible(true); //para que se vea
        this.grafo=grafo;
        /*
        this.dispose para borrar una vista
        
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tituloMenu1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        iniciarSimulaciónmenu1 = new javax.swing.JButton();
        eliminarElementosmenu1 = new javax.swing.JButton();
        verGrafomenu1 = new javax.swing.JButton();
        SalirMenu1 = new javax.swing.JButton();
        cargarGrafomenu1 = new javax.swing.JButton();

        jScrollPane1.setViewportView(jEditorPane1);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/ANT CARD sunset.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 26, -1, -1));

        tituloMenu1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tituloMenu1.setText("Simulación de Hormigas");
        getContentPane().add(tituloMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 89, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iniciarSimulaciónmenu1.setText("Iniciar simulación");
        iniciarSimulaciónmenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarSimulaciónmenu1ActionPerformed(evt);
            }
        });
        jPanel1.add(iniciarSimulaciónmenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 140, -1));

        eliminarElementosmenu1.setText("Modificar Grafo");
        eliminarElementosmenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarElementosmenu1ActionPerformed(evt);
            }
        });
        jPanel1.add(eliminarElementosmenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 140, 30));

        verGrafomenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/verGrafo1.png"))); // NOI18N
        verGrafomenu1.setText("Ver grafo");
        verGrafomenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verGrafomenu1ActionPerformed(evt);
            }
        });
        jPanel1.add(verGrafomenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 140, 210));

        SalirMenu1.setText("Salir");
        SalirMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirMenu1ActionPerformed(evt);
            }
        });
        jPanel1.add(SalirMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        cargarGrafomenu1.setText("Cargar Grafo");
        cargarGrafomenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarGrafomenu1ActionPerformed(evt);
            }
        });
        jPanel1.add(cargarGrafomenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 140, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarGrafomenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarGrafomenu1ActionPerformed
        Menu1CargarArchivo vCargarArch=new Menu1CargarArchivo(this);
        vCargarArch.setVisible(true);
    }//GEN-LAST:event_cargarGrafomenu1ActionPerformed

    private void iniciarSimulaciónmenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarSimulaciónmenu1ActionPerformed
        if(grafo.cantidad >= 4 && grafo.existeConexion(grafo.primero, grafo.ultimo) && grafo.cantidad <= 20){
            Menu2IntroducirCiclosHormigas vMenu2=new Menu2IntroducirCiclosHormigas(this);
            vMenu2.setVisible(true); 
        }else{
            JOptionPane.showMessageDialog(null, "No se pudo iniciar la simulacion ya que su grafo no cumple con los requisitos minimos\n1. Debe haber minimo 4 ciudades, con no mas que 20.\n2. Debe existir alguna conexion entre la ciudad inicial y la final (Nido y Comida)");
        }
        
    }//GEN-LAST:event_iniciarSimulaciónmenu1ActionPerformed

    private void verGrafomenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verGrafomenu1ActionPerformed
        VisualizadorGrafo x = new VisualizadorGrafo();
        x.GrafoVisualizador(grafo);

    }//GEN-LAST:event_verGrafomenu1ActionPerformed

    private void eliminarElementosmenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarElementosmenu1ActionPerformed

    Menu1ModificarGrafo vEliminar=new Menu1ModificarGrafo(this);
    vEliminar.setVisible(true);
    }//GEN-LAST:event_eliminarElementosmenu1ActionPerformed

    private void SalirMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirMenu1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_SalirMenu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu1AgregarEliminarCargarIniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu1AgregarEliminarCargarIniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu1AgregarEliminarCargarIniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu1AgregarEliminarCargarIniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu1AgregarEliminarCargarIniciar(grafo).setVisible(true);
            }
        });
    }

    public static Grafo getGrafo() {
        return grafo;
    }

    public static void setGrafo(Grafo grafo) {
        Menu1AgregarEliminarCargarIniciar.grafo = grafo;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SalirMenu1;
    private javax.swing.JButton cargarGrafomenu1;
    private javax.swing.JButton eliminarElementosmenu1;
    private javax.swing.JButton iniciarSimulaciónmenu1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel tituloMenu1;
    private javax.swing.JButton verGrafomenu1;
    // End of variables declaration//GEN-END:variables
}
