/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectograafo;
import GUI.*;

import javax.swing.JOptionPane;

/**
 *
 * @author CMGamer
 */
public class Menu1EliminarHormigasCiudades extends javax.swing.JFrame {
    public Grafo grafo = Menu1AgregarEliminarCargarIniciar.grafo; //tenemos que poner el mismo grafo static
    /**
     * Creates new form InterfazPrueba
     */
    
    public static Menu1AgregarEliminarCargarIniciar vEliminarHormigasCiudades;
    
    public Menu1EliminarHormigasCiudades(Menu1AgregarEliminarCargarIniciar vEliminarHormigasCiudades) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Entrada = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        eliminarHormiga = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Salida = new javax.swing.JTextArea();
        jButton8 = new javax.swing.JButton();
        volverMenu1menuCargar = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(Entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 430, 70));

        jButton3.setText("Eliminar Ciudad");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        eliminarHormiga.setText("Eliminar hormiga");
        eliminarHormiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarHormigaActionPerformed(evt);
            }
        });
        jPanel1.add(eliminarHormiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, -1));

        jButton7.setText("Mostrar Grafo");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, -1, -1));

        Salida.setColumns(20);
        Salida.setRows(5);
        jScrollPane1.setViewportView(Salida);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 420, 250));

        jButton8.setText("Eliminar Camino");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        volverMenu1menuCargar.setText("Volver a menú");
        volverMenu1menuCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverMenu1menuCargarActionPerformed(evt);
            }
        });
        jPanel1.add(volverMenu1menuCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, -1));

        jButton5.setText("Abrir Archivo");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        VisualizadorGrafo x = new VisualizadorGrafo();
        x.GrafoVisualizador(grafo);
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void eliminarHormigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarHormigaActionPerformed
        String origen = "";
        String destino = "";
        origen = JOptionPane.showInputDialog("Origen");
        destino = JOptionPane.showInputDialog("Destino");
        if(grafo.existeCiudad(origen) && grafo.existeCiudad(destino)){
            grafo.eliminarCamino(origen, destino);
        }
        Salida.setText(grafo.toString());
    }//GEN-LAST:event_eliminarHormigaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String dato= Entrada.getText();
        grafo.eliminarCiudad(dato);
        Salida.setText(grafo.toString());
        Entrada.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void volverMenu1menuCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverMenu1menuCargarActionPerformed
        setVisible(false);
        this.toBack();
        this.toFront();
        /**
        * @param false es para indicar que al devolverse en el programa, esta ventana "this" requiere irse.
        */
        /**
        * @param NORMAL en setState es para indicar que es la ventana referenciada es el estado "normal" de una aplicación.
        */
    }//GEN-LAST:event_volverMenu1menuCargarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        ImportaArchivo x = new ImportaArchivo();
        Grafo y = x.lectorDeArchivos();
        grafo = y;
        Salida.setText(grafo.toString());
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu1EliminarHormigasCiudades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu1EliminarHormigasCiudades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu1EliminarHormigasCiudades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu1EliminarHormigasCiudades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu1EliminarHormigasCiudades(vEliminarHormigasCiudades).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Entrada;
    private javax.swing.JTextArea Salida;
    private javax.swing.JButton eliminarHormiga;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton volverMenu1menuCargar;
    // End of variables declaration//GEN-END:variables
}
