/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectograafo;

import GUI.Menu1AgregarEliminarCargarIniciar;
import GUI.Menu2IntroducirCiclosHormigas;
import GUI.Menu3FinalizarGrafoGuardar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author CMGamer
 */
public class Menu2AgregarHormigasCiudades extends javax.swing.JFrame {
    JFrame warningCiudades;
    
    public static Menu2IntroducirCiclosHormigas vAgregarHormigasCiudades; 
    public Grafo grafo = Menu1AgregarEliminarCargarIniciar.grafo; //tenemos que poner el mismo grafo static
    /**
     * Creates new form InterfazPrueba
     */
    public Menu2AgregarHormigasCiudades(Menu2IntroducirCiclosHormigas vAgregarHormigasCiudades) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Entrada = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Salida = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        terminadaOperacion = new javax.swing.JButton();
        numerodeCiudades = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaActionPerformed(evt);
            }
        });
        jPanel1.add(Entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 260, 240));

        jButton1.setText("Agregar Ciudad");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        jButton2.setText("Agregar Camino");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jButton7.setText("Mostrar Grafo");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, -1, -1));

        Salida.setColumns(20);
        Salida.setRows(5);
        jScrollPane1.setViewportView(Salida);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 250, 250));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setText("Inserción de ciudades");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel13.setText("en anterior ventana.");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 680, -1));

        jLabel14.setText("Es necesario insertar manualmente los valores especificados, hasta alcanzar los valores de \"cantidad\" especificados");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 680, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("CANTIDAD REQUERIDA DE CIUDADES:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 10));

        terminadaOperacion.setText("Hecho (trabajar)");
        terminadaOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminadaOperacionActionPerformed(evt);
            }
        });
        jPanel1.add(terminadaOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, -1, -1));

        numerodeCiudades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerodeCiudadesActionPerformed(evt);
            }
        });
        jPanel1.add(numerodeCiudades, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                if(Integer.parseInt(numerodeCiudades.getText())!=0){
           String dato= Entrada.getText();
        grafo.nuevaCiudad(dato);
        Salida.setText(grafo.toString());
        Entrada.setText("");
           int numeroCiudadesactualizado=Integer.parseInt(numerodeCiudades.getText())-1;
           numerodeCiudades.setText(Integer.toString(numeroCiudadesactualizado));
        }else{
            warningCiudades=new JFrame();
            JOptionPane.showMessageDialog(warningCiudades, "Ya has introducido todas las ciudades necesarias!", "Alert", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String origen = "";
        String destino = "";
        float distancia;
        origen = JOptionPane.showInputDialog("Origen");
        destino = JOptionPane.showInputDialog("Destino");
        distancia = Float.parseFloat(JOptionPane.showInputDialog("Distancia"));
        if(grafo.existeCiudad(origen) && grafo.existeCiudad(destino)){
            grafo.nuevoCamino(origen, destino, distancia);
        }
        Salida.setText(grafo.toString());
    }//GEN-LAST:event_jButton2ActionPerformed

    
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        VisualizadorGrafo x = new VisualizadorGrafo();
        x.GrafoVisualizador(grafo);
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void EntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaActionPerformed

    private void terminadaOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminadaOperacionActionPerformed
Menu3FinalizarGrafoGuardar vMenu3=new Menu3FinalizarGrafoGuardar(this);
vMenu3.setVisible(true); //hola
this.toFront();        
    }//GEN-LAST:event_terminadaOperacionActionPerformed

    private void numerodeCiudadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numerodeCiudadesActionPerformed
        
    }//GEN-LAST:event_numerodeCiudadesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu2AgregarHormigasCiudades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu2AgregarHormigasCiudades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu2AgregarHormigasCiudades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu2AgregarHormigasCiudades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu2AgregarHormigasCiudades(vAgregarHormigasCiudades).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Entrada;
    private javax.swing.JTextArea Salida;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField numerodeCiudades;
    private javax.swing.JButton terminadaOperacion;
    // End of variables declaration//GEN-END:variables
}
